name: my-app

on:
  push:
    branches:
      - dfadfasfasf
#  event: [ event1, event2, ... ]
#  push:
#    branches:
#      - main
#      - develop
#  pull_request:
#    branches:
#      - main
#      - develop

jobs: # 병렬
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#  중간 코드 생략


#      - name: create remote directory
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ubuntu
#          key: ${{ secrets.KEY }}
#          script: |
#            sudo mkdir -p /home/ubuntu/srv/ubuntu
#            sudo chown -R ubuntu:ubuntu /home/ubuntu/srv/ubuntu
##            sudo rm -rf /home/ubuntu/srv/ubuntu
#          # sudo로 권한을 변경하면 소유자가 root가 되어버린다. ubuntu로 변경해줘야함
#
#      - name: copy source via ssh key
#        uses: burnett01/rsync-deployments@4.1 # rsync 로컬 전체 복사
#        with:
#          switches: -avzr --delete -a --include=".*" # --delete 원격 서버에 로컬에 없는거 지우기, -a 숨김파일 복사 ( .env )
#          remote_path: /home/ubuntu/srv/ubuntu/  /var/lib/docker
#          remote_host: ${{ secrets.HOST }}
#          remote_user: ubuntu
#          remote_key: ${{ secrets.KEY }}
#
#      - name: executing remote ssh commands using password
#        uses: appleboy/ssh-action@master
#        env:
#          HS512_SECRET: ${{ secrets.HS512_SECRET }}
#        with:
#          host: ${{ secrets.HOST }}
#          username: ubuntu
#          key: ${{ secrets.KEY }}
#          envs: HS512_SECRET
#          script: |
#            sudo sh /home/ubuntu/srv/ubuntu/deploy.sh