version: '3.9'
services:
  database:
  # EB 에서는 build 를 지원하지 않음
    image: ${DOCKERHUB_USERNAME}/my-app-db:${TAG_VERSION}
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_USER: ${HS512_SECRET}
      MYSQL_PASSWORD: ${HS512_SECRET}
      MYSQL_ROOT_PASSWORD: ${HS512_SECRET}
      MYSQL_DATABASE: ${HS512_SECRET}
    expose:
      - 3306
    ports:
      - "3306:3306"
    container_name: ${HS512_SECRET}


  springboot-server:
    depends_on:
      - database
    image: ${DOCKERHUB_USERNAME}/my-app-server:${TAG_VERSION}
    restart: always
    volumes:
      - ./springboot-server:/build/app
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: ${HS512_SECRET}
      MYSQL_USER: ${HS512_SECRET}
      MYSQL_PASSWORD: ${HS512_SECRET}
      MYSQL_DATABASE: ${HS512_SECRET}
      MYSQL_PORT: 3306
      HS512_SECRET: ${HS512_SECRET}

volumes:
  mysql-volume: