version: "3.8"
services:
  database:
    build: ./database
    image: my-app-db
    volumes:
      - mysql-volume:/var/lib/mysql
    hostname: database
    ports:
      - "3306:3306"    

  react-app:
    build: ./react-app
    image: my-app-react
    volumes:
      - ./react-app:/home/node/app
      - /home/node/app/node_modules # node_modules를 호스트 디렉토리와 공유하지 않도록함( 사라지지 않도록 )
    ports:
      - "80:3000"

  springboot-server:
    depends_on:
      - database
    build: ./springboot-server
    image: my-app-server
    volumes:
      - ./springboot-server:/build/app
    ports:
      - "8080:8080"

volumes:
  mysql-volume: