version: "3.8"
services:
  database:
    build: ./database
    image: my-app-db
    volumes:
      - mysql-volume:/var/lib/mysql
    hostname: database

    ports:
      - "3306:3306"

  springboot-server:
    depends_on:
      - database
    build: ./springboot-server
    image: my-app-server
    volumes:
      - ./springboot-server:/build/app
    ports:
      - "8080:8080"


volumes:
  mysql-volume: