version: "3.8"
services:
  database:
    image: ${DOCKERHUB_USERNAME}/my-app-db:${TAG_VERSION}
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    hostname: database
    env_file:
      - .env
    ports:
      - "3306:3306"

  springboot-server:
    depends_on:
      - database
    image: ${DOCKERHUB_USERNAME}/my-app-server:${TAG_VERSION}
    restart: always        
    volumes:
      - ./springboot-server:/build/app
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  mysql-volume: