server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?characterEncoding=utf-8&serverTimezone=Asia/Seoul&useSSL=true&enabledTLSProtocols=TLSv1.2
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
      # dialect: org.hibernate.dialect.MySQL8Dialect
      '[hibernate.format_sql]': true
      '[default_batch_fetch_size]': 100
    defer-datasource-initialization: true

  output:
    ansi:
      enabled: always

logging:
  level:
    '[org.springframework.boot.web]': DEBUG
    '[com.example]': DEBUG
