server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
# spring:
#   datasource:
#     url: jdbc:mysql://${DBHOST:localhost}:3306/visitlog
#     username: mysql_user
#     password: mysql_password
#     driver-class-name: com.mysql.cj.jdbc.Driver

  # security:
  #   user:
  #     name: ssar
  #     password: 1234

  sql:
    init:
      mode: always
      data-locations: classpath:static/db/insert_data.sql
      encoding: utf-8

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
      '[default_batch_fetch_size]': 100
    defer-datasource-initialization: true

  output:
    ansi:
      enabled: always

logging:
  level:
    '[org.springframework.boot.web]': DEBUG

meta:
  name: ${HS512_SECRET}

